### ISSUE TITLE
Framework independent

### ISSUE THREAD

**Issue by trans** [dcadenas/rubydeps#1]
You might be able to use an at_exit technique, or something similar to how coverage tools like simplecov work, instead of have to write special runner code for every supported test framework. That way any test framework could be used regardless.

**Comment by dcadenas** [comment]
On it, thanks

**Comment by dcadenas** [comment]
Done. So now you need to add Rubydeps.start in your test framework helper file and that should be enough. The executable file is still there to be able to play with filters on the dependency file. For the moment the start method doesn't accept a block, I think that's not needed for the moment.

Thanks for the feedback!

**Comment by trans** [comment]
Awesome! Thank you!

Now I can try it out with my [RubyTest](http://github.com/rubyworks/rubytest) based test libraries!
