### ISSUE TITLE
Troubles with Ruby 2.0

### ISSUE THREAD

**Issue by newmen** [dcadenas/rubydeps#5]
Hello.

I want use your beautiful gem for my project on Ruby 2.0 (with new syntax everywhere).
When i try to install gem, i had got some errors and first is that ruby_core_source can't download corresponding source file for 2.0, but i fixed it using github issues feature and good contribute mans :)
So, when valid source of 2.0 downloaded, your gem begins building native extension... and i get new error on it step:

```
[newmen@blackbox ~]$ gem install rubydeps
Building native extensions.  This could take a while...
ERROR:  Error installing rubydeps:
    ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.0.0-p0/bin/ruby extconf.rb
checking for vm_core.h... no
checking for vm_core.h... no
Requesting http://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p0.tar.gz
Downloading http://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p0.tar.gz
checking for vm_core.h... yes
checking for iseq.h... yes
creating Makefile

make
compiling call_site_analyzer.c
call_site_analyzer.c: In function ‘event_hook’:
call_site_analyzer.c:93:43: error: ‘rb_iseq_t’ has no member named ‘filepath’
make: *** [call_site_analyzer.o] Error 1
```

How i can fix it?
Thanks

**Comment by dcadenas** [comment]
Thanks for the feedback and sorry for the late response. It should be fixed now.

**Comment by newmen** [comment]
Thank you very much. This is very good news.
